config/routes.rb
Account::Application.routes.draw do
  resources :receipts

  resources :payments, :collection => { :update_payments => :put }

  resources :homes

  
  root :to => 'homes#index'

end

app/models/gst_cats.rb
class GstCats < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
  has_many :years
  accepts_nested_attributes_for :years, :allow_destroy => true, :reject_if => lambda { |a| a[:year].blank? }

end

app/models/pay_cat_codes.rb
class PayCatCodes < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/rec_cat_codes.rb
class RecCatCodes < ActiveRecord::Base
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/tax_year.rb
class TaxYear < ActiveRecord::Base
  belongs_to :home
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  
  set_tab :home
  
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  
  set_tab :payment
  
  set_tab :jul, :navigation
  set_tab :aug, :navigation
  set_tab :sep, :navigation
  
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :ok }
    end
  end
end

def update_payments
  Payment.update(params[:payment].keys, params[:payment].values)
  flash[:notice] = 'Payments were successfully updated.'
  redirect_to :action => "index"
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  # GET /receipts
  # GET /receipts.json
  
  set_tab :receipt
  
  def index
    @receipts = Receipt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(params[:receipt])

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/homes/_form.html.erb
<%= nested_form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_name %><br />
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :tfn %><br />
    <%= f.text_field :tfn %>
  </div>
  <div class="field">
    <%= f.label :email1 %><br />
    <%= f.text_field :email1 %>
  </div>
  <div class="field">
    <%= f.label :email2 %><br />
    <%= f.text_field :email2 %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :abn %><br />
    <%= f.text_field :abn %>
  </div>
  <div class="field">
    <%= f.label :street1 %><br />
    <%= f.text_field :street1 %>
  </div>
  <div class="field">
    <%= f.label :street2 %><br />
    <%= f.text_field :street2 %>
  </div>
  <div class="field">
    <%= f.label :suburb %><br />
    <%= f.text_field :suburb %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
    <%= f.number_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :current_tax_year_id %><br />
    <%= f.number_field :current_tax_year_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<h1>Listing homes</h1>

<table>
  <tr>
    <th>Business name</th>
    <th>Tfn</th>
    <th>Email1</th>
    <th>Email2</th>
    <th>Phone1</th>
    <th>Phone2</th>
    <th>Abn</th>
    <th>Street1</th>
    <th>Street2</th>
    <th>Suburb</th>
    <th>State</th>
    <th>Current year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @homes.each do |home| %>
  <tr>
    <td><%= home.business_name %></td>
    <td><%= home.tfn %></td>
    <td><%= home.email1 %></td>
    <td><%= home.email2 %></td>
    <td><%= home.phone1 %></td>
    <td><%= home.phone2 %></td>
    <td><%= home.abn %></td>
    <td><%= home.street1 %></td>
    <td><%= home.street2 %></td>
    <td><%= home.suburb %></td>
    <td><%= home.state_id %></td>
    <td><%= home.current_tax_year_id %></td>
    <td><%= link_to 'Show', home %></td>
    <td><%= link_to 'Edit', edit_home_path(home) %></td>
    <td><%= link_to 'Destroy', home, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Business name:</b>
  <%= @home.business_name %>
</p>

<p>
  <b>Tfn:</b>
  <%= @home.tfn %>
</p>

<p>
  <b>Email1:</b>
  <%= @home.email1 %>
</p>

<p>
  <b>Email2:</b>
  <%= @home.email2 %>
</p>

<p>
  <b>Phone1:</b>
  <%= @home.phone1 %>
</p>

<p>
  <b>Phone2:</b>
  <%= @home.phone2 %>
</p>

<p>
  <b>Abn:</b>
  <%= @home.abn %>
</p>

<p>
  <b>Street1:</b>
  <%= @home.street1 %>
</p>

<p>
  <b>Street2:</b>
  <%= @home.street2 %>
</p>

<p>
  <b>Suburb:</b>
  <%= @home.suburb %>
</p>

<p>
  <b>State:</b>
  <%= @home.state_id %>
</p>

<p>
  <b>Current year:</b>
  <%= @home.current_tax_year_id %>
</p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Account</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 
  <div id="tabs-main">
    <%= tabs_tag do |tab| %>
      <%= tab.home      'Home', "/homes#show" %>
      <%= tab.payment   'Payments', "/payments#update_payments" %>
      <%= tab.receipt   'Receipts', receipts_path %>
    <% end %>
  </div>
 


 
<br /><br />  
<%= yield %>

</body>
</html>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tax_year_id %><br />
    <%= f.number_field :tax_year_id %>
  </div>
  <div class="field">
    <%= f.label "day" %><br />
    <%= f.number_field :pay_day %>
  </div>
  <div class="field">
    <%= f.label :cat_code_id %><br />
    <%= f.number_field :cat_code_id %>
  </div>
  <div class="field">
    <%= f.label :pay_details %><br />
    <%= f.text_field :pay_details %>
  </div>
  <div class="field">
    <%= f.label :pay_method_id %><br />
    <%= f.number_field :pay_method_id %>
  </div>
  <div class="field">
    <%= f.label :ref_no %><br />
    <%= f.text_field :ref_no %>
  </div>
  <div class="field">
    <%= f.label :pay_amount %><br />
    <%= f.text_field :pay_amount %>
  </div>
  <div class="field">
    <%= f.label :gst_cat_id %><br />
    <%= f.number_field :gst_cat_id %>
  </div>
  <div class="field">
    <%= f.label :gst_amount %><br />
    <%= f.text_field :gst_amount %>
  </div>
  <div class="field">
    <%= f.label :priv_use_percent %><br />
    <%= f.text_field :priv_use_percent %>
  </div>
  <div class="field">
    <%= f.label :priv_use_amount %><br />
    <%= f.text_field :priv_use_amount %>
  </div>
  <div class="field">
    <%= f.label :pay_month %><br />
    <%= f.number_field :pay_month %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p>
<div id="tabs-paymonth">
  <%= tabs_tag :namespace => :navigation do |tab| %>
    <%= tab.jul   'Jul', payments_path %>
    <%= tab.aug   'Aug', receipts_path %>
    <%= tab.sep   'Sep', payments_path %>
  <% end %>
</div>
</p><br /><br /><br />
<table>
  <tr>
    <th>Tax year</th>
    <th>Cat code</th>
    <th>Pay details</th>
    <th>Pay method</th>
    <th>Ref no</th>
    <th>Pay amount</th>
    <th>Gst cat</th>
    <th>Gst amount</th>
    <th>Priv use percent</th>
    <th>Priv use amount</th>
    <th>Pay month</th>
    <th>Pay day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.tax_year_id %></td>
    <td><%= payment.cat_code_id %></td>
    <td><%= payment.pay_details %></td>
    <td><%= payment.pay_method_id %></td>
    <td><%= payment.ref_no %></td>
    <td><%= payment.pay_amount %></td>
    <td><%= payment.gst_cat_id %></td>
    <td><%= payment.gst_amount %></td>
    <td><%= payment.priv_use_percent %></td>
    <td><%= payment.priv_use_amount %></td>
    <td><%= payment.pay_month %></td>
    <td><%= payment.pay_day %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tax year:</b>
  <%= @payment.tax_year_id %>
</p>

<p>
  <b>Cat code:</b>
  <%= @payment.cat_code_id %>
</p>

<p>
  <b>Pay details:</b>
  <%= @payment.pay_details %>
</p>

<p>
  <b>Pay method:</b>
  <%= @payment.pay_method_id %>
</p>

<p>
  <b>Ref no:</b>
  <%= @payment.ref_no %>
</p>

<p>
  <b>Pay amount:</b>
  <%= @payment.pay_amount %>
</p>

<p>
  <b>Gst cat:</b>
  <%= @payment.gst_cat_id %>
</p>

<p>
  <b>Gst amount:</b>
  <%= @payment.gst_amount %>
</p>

<p>
  <b>Priv use percent:</b>
  <%= @payment.priv_use_percent %>
</p>

<p>
  <b>Priv use amount:</b>
  <%= @payment.priv_use_amount %>
</p>

<p>
  <b>Pay month:</b>
  <%= @payment.pay_month %>
</p>

<p>
  <b>Pay day:</b>
  <%= @payment.pay_day %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/payments/update_payments.html.erb
<% form_for :payment, :url => {:action => 'update_payments'} do -%>
  <table>
    <tr>
      <th>Current</th>
      <th>Publication date</th>
      <th>Name</th>
    </tr>
    <% @payments.each do |payment| %>
      <% fields_for "payment[]", report do |payment_fields| %>
    <tr>
      <td><%= payment_fields.tax_year_id %></td>
      <td><%= payment_fields.cat_code_id %></td>
      <td><%= payment_fields.pay_details %></td>

    </tr>
      <% end %>
    <% end %>
  </table>
 <%= submit_tag 'Update' %>
<% end %>

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tax_year_id %><br />
    <%= f.number_field :tax_year_id %>
  </div>
  <div class="field">
    <%= f.label :cat_code_id %><br />
    <%= f.number_field :cat_code_id %>
  </div>
  <div class="field">
    <%= f.label :rec_details %><br />
    <%= f.text_field :rec_details %>
  </div>
  <div class="field">
    <%= f.label :inv_rec_no %><br />
    <%= f.text_field :inv_rec_no %>
  </div>
  <div class="field">
    <%= f.label :rec_amount %><br />
    <%= f.text_field :rec_amount %>
  </div>
  <div class="field">
    <%= f.label :gst_cat_id %><br />
    <%= f.number_field :gst_cat_id %>
  </div>
  <div class="field">
    <%= f.label :gst_amount %><br />
    <%= f.text_field :gst_amount %>
  </div>
  <div class="field">
    <%= f.label :bankings %><br />
    <%= f.text_field :bankings %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :rec_month %><br />
    <%= f.number_field :rec_month %>
  </div>
  <div class="field">
    <%= f.label :rec_day %><br />
    <%= f.number_field :rec_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<h1>Listing receipts</h1>

<table>
  <tr>
    <th>Tax year</th>
    <th>Cat code</th>
    <th>Rec details</th>
    <th>Inv rec no</th>
    <th>Rec amount</th>
    <th>Gst cat</th>
    <th>Gst amount</th>
    <th>Bankings</th>
    <th>Comments</th>
    <th>Rec month</th>
    <th>Rec day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receipts.each do |receipt| %>
  <tr>
    <td><%= receipt.tax_year_id %></td>
    <td><%= receipt.cat_code_id %></td>
    <td><%= receipt.rec_details %></td>
    <td><%= receipt.inv_rec_no %></td>
    <td><%= receipt.rec_amount %></td>
    <td><%= receipt.gst_cat_id %></td>
    <td><%= receipt.gst_amount %></td>
    <td><%= receipt.bankings %></td>
    <td><%= receipt.comments %></td>
    <td><%= receipt.rec_month %></td>
    <td><%= receipt.rec_day %></td>
    <td><%= link_to 'Show', receipt %></td>
    <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
    <td><%= link_to 'Destroy', receipt, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tax year:</b>
  <%= @receipt.tax_year_id %>
</p>

<p>
  <b>Cat code:</b>
  <%= @receipt.cat_code_id %>
</p>

<p>
  <b>Rec details:</b>
  <%= @receipt.rec_details %>
</p>

<p>
  <b>Inv rec no:</b>
  <%= @receipt.inv_rec_no %>
</p>

<p>
  <b>Rec amount:</b>
  <%= @receipt.rec_amount %>
</p>

<p>
  <b>Gst cat:</b>
  <%= @receipt.gst_cat_id %>
</p>

<p>
  <b>Gst amount:</b>
  <%= @receipt.gst_amount %>
</p>

<p>
  <b>Bankings:</b>
  <%= @receipt.bankings %>
</p>

<p>
  <b>Comments:</b>
  <%= @receipt.comments %>
</p>

<p>
  <b>Rec month:</b>
  <%= @receipt.rec_month %>
</p>

<p>
  <b>Rec day:</b>
  <%= @receipt.rec_day %>
</p>


<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>